### ISSUE TITLE
The use of container instead of referenceContainer breaks the layout

### ISSUE THREAD

**Issue by jesse-deboer** [MultiSafepay/magewire-checkout#16]
Custom things inside of the `checkout.payment.section` container will be overwritten due to not using a referenceContainer but overwriting it.

I made a fix here: https://github.com/MultiSafepay/magewire-checkout/pull/15/files

**Comment by Vinod-MultiSafepay** [comment]
Thanks @jesse-deboer , i've merged the change!

**Comment by vinodsowdagar** [comment]
Hi.
 
We made a release which contains the changes discussed.
 
Please, consider we move this package to ["multisafepay/magento2-hyva-checkout"](https://github.com/MultiSafepay/magento2-hyva-checkout/).
 
This one is now declared as abandoned, and you should still be capable to upgrade to version 2.0.0. However we recommend you to upgrade your dependency pointing to the new package.
 
Thanks again for your contribution and contacting us.
