### ISSUE TITLE
The preselected method is not set

### ISSUE THREAD

**Issue by jesse-deboer** [MultiSafepay/magewire-checkout#17]
In the MultiSafepay module there is the option to set a preselected method in the admin. You can get this preselected method by using: `getPreselectedMethod` inside of the `config.php` file.

**Comment by jesse-deboer** [comment]
Fixed in https://github.com/MultiSafepay/magewire-checkout/pull/18 !

**Comment by Vinod-MultiSafepay** [comment]
@jesse-deboer Thanks for the PR, we are very happy with it. I've left some feedback, mostly related to backwards incompatibility with PHP 7.4.

**Comment by vinodsowdagar** [comment]
Hi.
 
We made a release which contains the changes discussed.
 
Please, consider we move this package to ["multisafepay/magento2-hyva-checkout"](https://github.com/MultiSafepay/magento2-hyva-checkout/).
 
This one is now declared as abandoned, and you should still be capable to upgrade to version 2.0.0. However we recommend you to upgrade your dependency pointing to the new package.
 
Thanks again for your contribution and contacting us.
