### ISSUE TITLE
.CRITICAL: Magewire: Warning: Undefined array key "issuer_id"

### ISSUE THREAD

**Issue by jesse-deboer** [MultiSafepay/magewire-checkout#19]
The first option in the select box will be selected, but it will not be set on Magewire if you don't select one yourself. 

This means that if you click on iDeal and the first issuer is your bank it won't set it, and give this error when you checkout. The first option should be an empty one that is disabled or it should set the first issuer as the issuer.

**Comment by jesse-deboer** [comment]
https://github.com/MultiSafepay/magewire-checkout/pull/21

**Comment by Vinod-MultiSafepay** [comment]
Thanks, it's merged!

**Comment by vinodsowdagar** [comment]
Hi.
 
We made a release which contains the changes discussed.
 
Please, consider we move this package to ["multisafepay/magento2-hyva-checkout"](https://github.com/MultiSafepay/magento2-hyva-checkout/).
 
This one is now declared as abandoned, and you should still be capable to upgrade to version 2.0.0. However we recommend you to upgrade your dependency pointing to the new package.
 
Thanks again for your contribution and contacting us.
