### ISSUE TITLE
Embed payment methods directly into your checkout

### ISSUE THREAD

**Issue by geoffreycbarber** [MultiSafepay/magewire-checkout#23]
As discussed with @Vinod-MultiSafepay on slack, the module currently does not implement Payment components - https://docs.multisafepay.com/docs/payment-components

It was mentioned this would be worked on in the next couple of weeks.

Could you let us know when this is feature is released?

Cheers

**Comment by vinodsowdagar** [comment]
Hi.
 
We made a release which contains the changes discussed.
 
Please, consider we move this package to ["multisafepay/magento2-hyva-checkout"](https://github.com/MultiSafepay/magento2-hyva-checkout/).
 
This one is now declared as abandoned, and you should still be capable to upgrade to version 2.0.0. However we recommend you to upgrade your dependency pointing to the new package.
 
Thanks again for your contribution and contacting us.
