### ISSUE TITLE
Add payment method icons to the checkout

### ISSUE THREAD

**Issue by xgerhard** [MultiSafepay/magewire-checkout#24]
Hi, could payment method icons be added to the checkout? 
See: https://docs.hyva.io/checkout/hyva-checkout/devdocs/payment-integration-api.html#payment-method-icon

**Comment by vinodsowdagar** [comment]
Hi.
 
We made a release which contains the changes discussed.
 
Please, consider we move this package to ["multisafepay/magento2-hyva-checkout"](https://github.com/MultiSafepay/magento2-hyva-checkout/).
 
This one is now declared as abandoned, and you should still be capable to upgrade to version 2.0.0. However we recommend you to upgrade your dependency pointing to the new package.
 
Thanks again for your contribution and contacting us.
